# Generated by Django 5.1.7 on 2025-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assign_type',
            field=models.CharField(choices=[('all', 'Всем'), ('students', 'Студентам'), ('staff', 'Сотрудникам')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
