# Generated by Django 5.1.7 on 2025-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0002_test_assign_type_test_direction_test_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='test',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='test',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='test',
            name='profile',
        ),
        migrations.AlterField(
            model_name='test',
            name='assign_type',
            field=models.CharField(choices=[('all', 'Всем'), ('students', 'Студентам'), ('staff', 'Сотрудникам'), ('guests', 'Гостям')], default='all', max_length=20),
        ),
    ]
