# Generated by Django 5.1.7 on 2025-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0004_remove_test_assign_type_test_assigned_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
