# Generated by Django 5.1.7 on 2025-06-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0005_staff_is_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
