# Generated by Django 5.1.7 on 2025-06-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0006_guest_is_admin_user_student_is_admin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_admin_user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_admin_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin_user',
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID в Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя в Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Telegram',
                'verbose_name_plural': 'Профили Telegram',
            },
        ),
    ]
