# Generated by Django 5.1.7 on 2025-06-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0007_remove_guest_is_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудник'},
        ),
    ]
