# Generated by Django 5.1.7 on 2025-06-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0009_alter_guest_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Ответ - один из списка', 'verbose_name_plural': 'Ответы - один из списка'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Все возможные результаты'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'verbose_name': 'Ответ - шкала', 'verbose_name_plural': 'Ответы - шкала'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Балл за вопрос', 'verbose_name_plural': 'Баллы за вопросы'},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Результат тестирования', 'verbose_name_plural': 'Результаты тестирования'},
        ),
    ]
